//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryService
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        public book()
        {
            this.readbook = new HashSet<readbook>();
            this.wishlist = new HashSet<wishlist>();
        }
    
        public int bookID { get; set; }
        public string bookName { get; set; }
        public string authorName { get; set; }
    
        public virtual ICollection<readbook> readbook { get; set; }
        public virtual ICollection<wishlist> wishlist { get; set; }
    }
}
