//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryService
{
    using System;
    using System.Collections.Generic;
    
    public partial class wishlist
    {
        public int wishlistID { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> bookID { get; set; }
    
        public virtual book book { get; set; }
        public virtual user user { get; set; }
    }
}
